"""Add user verification fields with defaults

Revision ID: 615db783dbd8
Revises: e95a2f7339c8
Create Date: 2025-10-20 18:26:26.492782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615db783dbd8'
down_revision = 'e95a2f7339c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('verification_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_date', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_date')
        batch_op.drop_column('verification_photo')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
